services:
  backend:
    image: ghcr.io/fanos-dev/omwebproject/backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - app-net

  frontend:
    image: ghcr.io/fanos-dev/omwebproject/frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BACKEND_API_URL=http://backend:8081
      - BACKEND_URL=http://backend:8081
    depends_on:
      - backend
    networks:
      - app-net

networks:
  app-net:
    driver: bridge